(defun grade (percent)
  (cond
    ((and (<= percent 100) (>= percent 90))
     "A+")
    ((and (<= percent 89) (>= percent 85))
     "A")
    ((and (<= percent 84) (>= percent 80))
     "A-")
    ((and (<= percent 79) (>= percent 77))
     "B+")
    ((and (<= percent 76) (>= percent 73))
     "B")
    ((and (<= percent 72) (>= percent 70))
     "B-")
    ((and (<= percent 69) (>= percent 0))
    "F")))
